name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libtinfo5
        pip install buildozer cython==0.29.33 virtualenv

    - name: Build APK
      run: |
        cd projectAN
        buildozer -v android release
        ls -la ./bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4  # تغییر نسخه از v3 به v4
      with:
        name: music-player-apk
        path: ./projectAN/bin/*.apk
