name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
    
    - name: Set up Android SDK and NDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: "23.1.7779620"  # NDK 23b
        sdk-platform: "android-31"
        sdk-build-tools: "31.0.0"
    
    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.19
    
    - name: Run Buildozer
      run: |
        buildozer -v android debug
        ls -la bin/
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: music-player-apk
        path: bin/*.apk
